version: '3.8'

services:
  gitgulf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitgulf-dev
    working_dir: /app
    volumes:
      - .:/app
      - gitgulf-build:/app/.build
    environment:
      SWIFT_VERSION: '5.10'
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  gitgulf-build:
    driver: local
